#ifndef USB_IDS_H
#define USB_IDS_H

#include <stdint.h>

enum usb_vendor_id {
  USB_VENDOR_INTEL = 0x8087,
  USB_VENDOR_LOGITECH = 0x046D,
  USB_VENDOR_MICROSOFT = 0x045E,
  USB_VENDOR_SANDISK = 0x0781,
  USB_VENDOR_KINGSTON = 0x0951,
  USB_VENDOR_FTDI = 0x0403,
  USB_VENDOR_PROLIFIC = 0x067B,
  USB_VENDOR_QEMU = 0x0627,
};

enum usb_product_id {
  USB_PRODUCT_INTEL_USB3_HUB = 0x0024,
  USB_PRODUCT_LOGITECH_UNIFYING = 0xC52B,
  USB_PRODUCT_LOGITECH_K120 = 0xC31C,
  USB_PRODUCT_MICROSOFT_XBOX_360 = 0x028E,
  USB_PRODUCT_SANDISK_CRUZER = 0x5567,
  USB_PRODUCT_KINGSTON_DATATRAVELER = 0x1666,
  USB_PRODUCT_FTDI_SERIAL = 0x6001,
  USB_PRODUCT_PROLIFIC_PL2303 = 0x2303,
  USB_PRODUCT_QEMU_TABLET = 0x0001,
};

enum usb_class_code {
  USB_CLASS_PER_INTERFACE = 0x00,
  USB_CLASS_AUDIO = 0x01,
  USB_CLASS_COMM = 0x02,
  USB_CLASS_HID = 0x03,
  USB_CLASS_PHYSICAL = 0x05,
  USB_CLASS_IMAGE = 0x06,
  USB_CLASS_PRINTER = 0x07,
  USB_CLASS_MASS_STORAGE = 0x08,
  USB_CLASS_HUB = 0x09,
  USB_CLASS_CDC_DATA = 0x0A,
  USB_CLASS_SMART_CARD = 0x0B,
  USB_CLASS_VIDEO = 0x0E,
  USB_CLASS_WIRELESS = 0xE0,
  USB_CLASS_MISCELLANEOUS = 0xEF,
  USB_CLASS_VENDOR_SPEC = 0xFF,
};

enum usb_hid_subclass {
  USB_HID_SUBCLASS_NONE = 0x00,
  USB_HID_SUBCLASS_BOOT = 0x01,
};

enum usb_hid_protocol {
  USB_HID_PROTOCOL_NONE = 0x00,
  USB_HID_PROTOCOL_KEYBOARD = 0x01,
  USB_HID_PROTOCOL_MOUSE = 0x02,
};

enum usb_mass_subclass {
  USB_MASS_SUBCLASS_RBC = 0x01,
  USB_MASS_SUBCLASS_ATAPI = 0x02,
  USB_MASS_SUBCLASS_QIC = 0x03,
  USB_MASS_SUBCLASS_UFI = 0x04,
  USB_MASS_SUBCLASS_SFF8070 = 0x05,
  USB_MASS_SUBCLASS_SCSI = 0x06,
  USB_MASS_SUBCLASS_VENDOR_SPEC = 0xFF,
};

enum usb_mass_protocol {
  USB_MASS_PROTOCOL_CBI = 0x00,
  USB_MASS_PROTOCOL_CBI_NO_INTERRUPT = 0x01,
  USB_MASS_PROTOCOL_BULK_ONLY = 0x50,
};

#endif
