#!/usr/bin/env python3
"""Emit the kernel symbol table consumed by kernel/utilities/symtab.c.

usage: gen_symtab.py <kernel_nosyms.elf> <out.c>

Second pass of the two-pass link: the addresses only exist once everything
else has been laid out, so this reads them back out of the intermediate ELF
and writes a C file that the final link pulls in.

Offsets are stored relative to _kernel_start rather than as absolute
addresses. Adding the table grows .ksymtab and shifts nothing before it, so
the offsets computed here stay correct in the final link even though every
absolute address may move — which is what makes one extra pass sufficient
instead of iterating to a fixed point.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

# Text symbols only: the table answers "which function is this return
# address inside", so data and BSS entries would just be noise that the
# binary search could land on.
TEXT_TYPES = set("tTwW")

# Linker-defined markers and the table's own symbols. Emitting these would
# have them resolve to themselves in a backtrace.
SKIP = {"_kernel_start", "_kernel_end", "__ksymtab", "__ksymtab_count",
        "__ksymtab_start", "__ksymtab_end"}

LINE = re.compile(r"^([0-9a-fA-F]+)\s+([A-Za-z])\s+(\S+)$")


def read_symbols(elf: str) -> list[tuple[int, str, str]]:
    nm = os.environ.get("NM", "x86_64-elf-nm")
    try:
        out = subprocess.run([nm, "-n", elf], capture_output=True, text=True,
                             check=True).stdout
    except FileNotFoundError:
        sys.exit(f"gen_symtab: {nm} not found (set NM to override)")
    except subprocess.CalledProcessError as exc:
        sys.exit(f"gen_symtab: {nm} failed: {exc.stderr.strip()}")

    syms = []
    for line in out.splitlines():
        m = LINE.match(line.strip())
        if m:
            syms.append((int(m.group(1), 16), m.group(2), m.group(3)))
    return syms


def c_string(name: str) -> str:
    return '"' + name.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if len(sys.argv) != 3:
        sys.exit(__doc__.splitlines()[2])
    elf, out_path = sys.argv[1], sys.argv[2]

    syms = read_symbols(elf)
    if not syms:
        sys.exit(f"gen_symtab: no symbols in {elf}")

    base = next((a for a, _t, n in syms if n == "_kernel_start"), None)
    if base is None:
        sys.exit("gen_symtab: _kernel_start not found — is this the kernel ELF?")

    # One entry per address. Aliases at the same address are common (a
    # function and its .cold split, say); the first name after sorting wins
    # so the choice is at least deterministic.
    seen: dict[int, str] = {}
    for addr, typ, name in syms:
        if typ not in TEXT_TYPES or name in SKIP or addr < base:
            continue
        seen.setdefault(addr - base, name)

    entries = sorted(seen.items())

    with open(out_path, "w", newline="\n") as f:
        f.write("/* Generated by scripts/gen_symtab.py — do not edit.\n"
                " *\n"
                f" * {len(entries)} text symbols from {os.path.basename(elf)},\n"
                " * offsets relative to _kernel_start, sorted ascending so\n"
                " * symtab_resolve() can binary-search them.\n"
                " */\n"
                "#include <utilities/symtab.h>\n\n"
                "const struct ksym __ksymtab[] "
                "__attribute__((section(\".ksymtab\"), used)) = {\n")
        for off, name in entries:
            f.write(f"    {{ 0x{off:x}, {c_string(name)} }},\n")
        f.write("};\n\n"
                "const size_t __ksymtab_count =\n"
                "    sizeof(__ksymtab) / sizeof(__ksymtab[0]);\n")

    print(f"gen_symtab: {len(entries)} symbols -> {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
